//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using interopservices = System.Runtime.InteropServices;
#if NET_CF20


[assembly: ServiceDeclaration(DssServiceDeclaration.Proxy, SourceAssemblyKey="cf.genericgps.y2008.m03, version=0.0.0.0, culture=neutral, publickeytoken=4b35d66b62" +
    "e90db3")]

#else


[assembly: ServiceDeclaration(DssServiceDeclaration.Proxy, SourceAssemblyKey="genericgps.y2008.m03, version=0.0.0.0, culture=neutral, publickeytoken=4b35d66b62" +
    "e90db3")]

#endif
[assembly: System.Security.SecurityTransparentAttribute()]
[assembly: System.Security.AllowPartiallyTrustedCallersAttribute()]
[assembly: interopservices.ComVisible(true)]


