;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  boolean.INC                               ;
;                             Boolean Definitions                            ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the boolean definitions for all of the assembly code for
;	the 80188 MP3 Player.
;
; Revision History:

;     5/2/2008 Samuel Yang     


TRUE EQU 1h
FALSE EQU 0h
