//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using genericcompass = RoboMagellan.GenericCompass;


namespace RoboMagellan.GenericCompass
{
    
    
    /// <summary>
    /// GenericCompass Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        public const String Identifier = "http://schemas.tempuri.org/2008/05/genericcompass.html";
    }
    
    /// <summary>
    /// The GenericCompass State
    /// </summary>
    [DataContract()]
    public class GenericCompassState
    {
        private CompassData _dat;

        [DataMember]
        public CompassData currentAngle
        {
            get { return _dat; }
            set { _dat = value; }
        }
    }
    
    /// <summary>
    /// GenericCompass Main Operations Port
    /// </summary>
    [ServicePort()]
    public class GenericCompassOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get, Subscribe, CompassNotification>
    {
    }


    public class Subscribe : Subscribe<SubscribeRequestType, PortSet<SubscribeResponseType, Fault>, GenericCompassOperations> { }

    public class CompassNotification : Update<CompassData, DsspResponsePort<DefaultUpdateResponseType>>
    {
        public CompassNotification(CompassData d)
        {
            this.Body = d;
        }

        public CompassNotification() { }
    }

    [DataContract()]
    public struct CompassData
    {
        private int _angle;

        [DataMember]
        public int angle
        {
            get
            {
                return _angle;
            }

            set
            {
                _angle = value;
            }
        }
    }

    /// <summary>
    /// GenericCompass Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<GenericCompassState, Fault>>
    {
        
        /// <summary>
        /// GenericCompass Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// GenericCompass Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// GenericCompass Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<GenericCompassState,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }
}
