/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class webcamjava_Webcam */

#ifndef _Included_webcamjava_Webcam
#define _Included_webcamjava_Webcam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     webcamjava_Webcam
 * Method:    start_camera
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_webcamjava_Webcam_start_1camera
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     webcamjava_Webcam
 * Method:    capture_frame
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_webcamjava_Webcam_capture_1frame
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     webcamjava_Webcam
 * Method:    stop_camera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_webcamjava_Webcam_stop_1camera
  (JNIEnv *, jclass);

/*
 * Class:     webcamjava_Webcam
 * Method:    test_camera
 * Signature: (Ljava/lang/String;[III)V
 */
JNIEXPORT void JNICALL Java_webcamjava_Webcam_test_1camera
  (JNIEnv *, jclass, jstring, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
